#!/bin/bash

if [[ $(/usr/bin/docker ps |grep gni-mysql) ]]; then
  /usr/bin/docker exec gni-mysql /stop.sh
fi
sleep 1
if [[ $(/usr/bin/docker ps |grep gni-mysql) ]]; then
  /usr/bin/docker stop gni-mysql
fi
if [[ $(/usr/bin/docker ps -a |grep gni-mysql) ]]; then
  /usr/bin/docker rm gni-mysql
fi
